### ISSUE TITLE
Question: callback on SSO

### ISSUE THREAD

**Issue by keesvanbemmel** [becem-gharbi/directus-starter#2]
Hi!

Thanks for this starter!!

Quick question: if SSO signin is successful it is redirected to the callback.vue component. However, that component does nothing as far as I'm concerned. What should it do?

Regards,

Kees.

**Comment by becem-gharbi** [comment]
Hi, can you make the app is served on `127.0.0.1` and not `localhost`.

**Comment by keesvanbemmel** [comment]
Uh, sure, but that doesn't change the behaviour of the callback component? I'm also running it in a cloud with specific domain by the way with the same behaviour.

**Comment by becem-gharbi** [comment]
After a successfull SSO login the module redirects to the `callback` page, then performs the refresh of access token, finally redirects to `home` page (or previously visited protected page). If SSR enabled the `callback` page won't be rendered, so `home` page is directly shown. If SSR disabled the `callback` page is shown while performing refresh, then redirected to the `home` page.

So if the `callback` page is shown without an error as query parameter, then this means the refresh has failed.

The refresh fails in 2 cases, I have mentioned this on [readme](https://github.com/becem-gharbi/nuxt-directus#auth).
- The refresh token cookie is not found, this means that Directus and Nuxt are not sharing the same domain name.
- In development domain is not `127.0.0.1`, this is an `ofetch` [issue](https://github.com/unjs/ofetch/issues/156).

**Comment by keesvanbemmel** [comment]
I'm seeing a "directus_refresh_token" cookie in the application data, but the POST to directus /auth/refresh returns a 400 error with this:
```
{
    "errors": [
        {
            "message": "Invalid payload. \"refresh_token\" is required in either the JSON payload or Cookie.",
            "extensions": {
                "code": "INVALID_PAYLOAD",
                "reason": "\"refresh_token\" is required in either the JSON payload or Cookie"
            }
        }
    ]
}
```

![CleanShot 2023-09-07 at 11 12 48@2x](https://github.com/becem-gharbi/directus-starter/assets/4633876/d0a3bf29-1214-435e-9d42-ee40bfcb204e)

**Comment by keesvanbemmel** [comment]
Nevermind! Same site cookie config 👯 

Thanks for your time man!
