### ISSUE TITLE
date-fns-tz issue

### ISSUE THREAD

**Issue by Loosie94** [becem-gharbi/directus-starter#3]
Hi, i'm getting the error: 

` ERROR  Cannot start nuxt:  Missing "./esm/formatInTimeZone" specifier in "date-fns-tz" package`

After running npm install and then npm run dev. 
Any idea what is causing this?

**Comment by becem-gharbi** [comment]
Please upgrade to latest this pkg `@bg-dev/nuxt-naiveui`. https://github.com/becem-gharbi/nuxt-naiveui/releases/tag/v1.5.1

**Comment by Loosie94** [comment]
That did the trick with NPM. With Yarn I was getting: 
`Failed to resolve import "@vue/apollo-composable" from "node_modules/nuxt-apollo/dist/runtime/plugins/apolloWithWs.client.mjs`

Using NPM for now. Thanks!

**Comment by becem-gharbi** [comment]
This related to `nuxt-apollo` -> https://github.com/becem-gharbi/nuxt-apollo#known-issue
