### ISSUE TITLE
Authentication fails every-time the page is refreshed

### ISSUE THREAD

**Issue by moseskamau338** [becem-gharbi/directus-starter#7]
This might be a misconfiguration on my end but I could not find anything straight-forward to guide.

---

**Issue Description:**

When using Directus with a separate front-end application (this starter template), I encountered an issue where upon refreshing the page after login, I am redirected back to the login screen.

**Expected Behavior:**

After successful login, I expect to remain authenticated and not be redirected to the login screen upon page refresh.

**Actual Behavior:**

After logging in and refreshing the page, the authentication state is not persisted, and I am redirected to the login screen again.
At this point, the refresh cookie that was set is removed/deleted and login status set to false

**Steps to Reproduce:**

1. Set up a Directus instance on a VPS.
2. Develop a separate front-end application that interacts with the Directus API for authentication and data management.
3. Log in to the front-end application.
4. Refresh the page.

**Additional Context:**

- I've tried adjusting the session and cookie settings in the Directus environment, but the issue persists.
- I'm experiencing this problem both in my local development environment (localhost) and on the hosted domain.
- The issue occurs consistently across different browsers and projects

**Environment:**

- Directus version:10.8.3 and 10.9.3
- Front-end framework/library: Nuxt 3, [nuxt-directus](https://github.com/becem-gharbi/nuxt-directus)

**Comment by moseskamau338** [comment]
I also should mention that am using the latest packages for auth

**Comment by becem-gharbi** [comment]
I'm not able to reproduce the issue with this template. Please first make sure to pull the latest changes and check the auth notes in README.

**Comment by moseskamau338** [comment]
I could be missing something. Here is my .env file

```env
NODE_OPTIONS=--dns-result-order=ipv4first
DIRECTUS_REST_BASE_URL=https://portal.rintelex.com
DIRECTUS_WEB_TOKEN=< code >
NUXT_BASE_URL=https://rintelex.com
DIRECTUS_GRAPHQL_HTTP_ENDPOINT=https://portal.rintelex.com/graphql
DIRECTUS_GRAPHQL_WS_ENDPOINT=wss://portal.rintelex.com/graphql

DIRECTUS_ORG_ADMIN_ROLE=< code >
DIRECTUS_DEFAULT_ROLE_ID=< code >
MAINTENANCE_MODE=false
DIRECTUS_NOTICE_FOLDER=< code >
DIRECTUS_REGISTRY_FOLDER=< code >
```

```ts
//config/directus.ts

import type { ModuleOptions } from '@bg-dev/nuxt-directus'

export const directus: Partial<ModuleOptions> = {
  rest: {
    baseUrl: process.env.DIRECTUS_REST_BASE_URL!,
    nuxtBaseUrl: process.env.NUXT_BASE_URL!
  },

  graphql: {
    enabled: true,
    httpEndpoint: process.env.DIRECTUS_GRAPHQL_HTTP_ENDPOINT!,
    wsEndpoint: process.env.DIRECTUS_GRAPHQL_WS_ENDPOINT
  },

  auth: {
    enabled: true,
    mode: 'cookie', // Auth mode 'json' or 'cookie'
    enableGlobalAuthMiddleware: false,
    refreshTokenCookieName: 'directus_refresh_token',
    loggedInFlagName: 'directus_logged_in',
    msRefreshBeforeExpires: 3000,
    userFields: ['*', '*.*', 'associations.Association_id', 'associations.Association_id.*'],
    redirect: {
      callback: '/auth/callback',
      home: '/dashboard',
      login: '/auth/login',
      logout: '/auth/login',
      resetPassword: '/auth/reset-password'
    }
  }
}
```


It logs in fine but immediately I refresh, everything clears

Here is the Directus env (partially)
```env
REFRESH_TOKEN_COOKIE_DOMAIN=localhost
REFRESH_TOKEN_COOKIE_NAME=directus_refresh_token
REFRESH_TOKEN_COOKIE_SAME_SITE=None
REFRESH_TOKEN_COOKIE_SECURE=false
```

**Comment by becem-gharbi** [comment]
The refresh token cookie domain should be the same as your nuxt app.

```env
REFRESH_TOKEN_COOKIE_DOMAIN= rintelex.com
REFRESH_TOKEN_COOKIE_NAME= directus_refresh_token
REFRESH_TOKEN_COOKIE_SAME_SITE= Lax
REFRESH_TOKEN_COOKIE_SECURE= true
```

**Comment by moseskamau338** [comment]
Great! This worked for the deployed instance, how about localhost?

**Comment by becem-gharbi** [comment]
The frontend and backend should be on the same domain to send cookies.

**Comment by docloulou** [comment]
> The frontend and backend should be on the same domain to send cookies.

Hi, is there any way to get it to work with a different backend URL?
my config :
for dev: frontend nuxt is on localhost
backend dev api is on a rpi server (192.168.X.X:8055)

Thanks

**Comment by becem-gharbi** [comment]
> Hi, is there any way to get it to work with a different backend URL?

The SameSite attribute should be set to `none` to allow sending cookies on cross-site requests. The default Directus configuration is `lax` which is safe as it prevents leaking refresh and session tokens on cross-site requests. 

In your Directus **development server** you can set the following env variables
```env
REFRESH_TOKEN_COOKIE_SAME_SITE= none
SESSION_COOKIE_SAME_SITE = none
```
